# Dockerfile.dev
FROM node:24.11.0-alpine

# Install build tools
RUN apk add --no-cache libc6-compat git python3 make g++

WORKDIR /app


# Copy package files
COPY package*.json ./

# Copy Prisma schema FIRST (before npm install)
COPY prisma ./prisma/

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Expose port
EXPOSE 3000

# Start development server
CMD ["npm", "run", "dev"]